name: streamlit
channels:
  - conda-forge
  - defaults
dependencies:
  - streamlit 
  - pandas 
  - numpy 
  - shapely 
  - geopy
  - pandas 
  - scipy 
  - python-dotenv 
  - geopandas 
  - folium
  - streamlit-folium
